development:
  access_key_id: "AKIAJO5UTSRLEIV7GYGQ"
  secret_access_key: "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"
  bucket: "rentalmarketplace"

production:
  access_key_id: "AKIAJO5UTSRLEIV7GYGQ"
  secret_access_key: "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"
  bucket: "rentalmarketplace"
